### ISSUE TITLE
Example shows confusing use of strings vs. generator

### ISSUE THREAD

**Issue by fatuhoku** [jsverify/jsverify#94]
`jsc.forall` accepts generators. However, the first thing a newbie user sees is the following:

```js
jsc.forall("bool -> bool", "bool", function (f, b) {
    return f(f(f(b))) === f(b);
  });
```

I'm led to think that you're actually supposed to put the string `"bool -> bool"` as the first argument. Is there any way we can clarify this?

**Comment by StoneCypher** [comment]
That is what you put as the first argument, yes.

To clarify this, try it, and see that it works.

**Comment by phadej** [comment]
There is: https://github.com/jsverify/jsverify#dsl-for-input-parameters

**Comment by phadej** [comment]
@fatuhoku does that documentation section helps at all, or should we try to improve it.

At least I should expand it with a bit more examples.

**Comment by fatuhoku** [comment]
@phadej it may just be me being new to Javascript — the documentation calls the use of strings in place of the actual expected values a 'DSL' but I didn't really think it was one.

What I understand as a (e)DSL is something like https://github.com/Masonry/Masonry.

**Comment by phadej** [comment]
@fatuhoku *DSL (domain specific language)* is a broader term then *EDSL (embedded domain specific language)*. The latter inherits the syntax and constructs of the host language, e.g. Masonry is EDSL, a library in objective-c. The former (DSL) can be anything.

In *jsverify* case we can construct generators using JavaScript, .e.g `jsc.array(jsc.nat)`. One could say that is EDSL. Or than you can use a bit different language: `"array nat"`, which isn't embedded anymore.

---

There is possibility of confusion, but I don't know how to explain this more clearly; I can put the text above in a footnote of README if it does clarifies even a bit.

**Comment by StoneCypher** [comment]
@fatuhoku A "domain specific language" is just a language which is purposed to a task, rather than a language whose usage is open ended (a "general purpose language.")  SQL and Postscript are DSLs (postscript walks the line - it can do shit like opening files and sockets;) most programming languages are general purpose languages, instead.

CSS is a DSL.  Javascript is not.

**Comment by StoneCypher** [comment]
In general, the useful cutting criterion is "do whole chunks of software not make sense in this language?"

It doesn't make sense to implement a database or an operating system kernel under CSS; it doesn't make sense to implement an eReader in SQL; it doesn't make sense to implement an email parser in a computer algebra system; it doesn't make sense to implement a BIOS in Hypercard; it doesn't make sense to implement a chess UI in an expert systems language; et cetera.

Not "this would be a bad choice."  It would be a bad choice to write a web browser in Erlang because Erlang's access to UI controls is so painful.  But it can be done.

I mean "this literally isn't a goal that can be considered."

If that's a common outcome, then you're almost certainly looking at a DSL.

POV-Ray is a DSL.  Prolog is not.

**Comment by fatuhoku** [comment]
Point well made.
